version: "3.8"

services:
  app:
    build:
      context: .
      target: base
    volumes:
      - ./:/app
    command: compare --help

  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    command: bash
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      target: test
    volumes:
      - ./:/app
    command: pytest

  lint:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    command: sh -c "ruff . && black --check . && isort --check . && mypy ."

  # Example of running a specific comparison
  compare:
    build:
      context: .
      target: base
    volumes:
      - ./:/app
      - ${SOURCE_DIR:-./examples/source}:/source
      - ${TARGET_DIR:-./examples/target}:/target
    command: compare --source /source --target /target --output-format html
