name: aether
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.0.4
  - numpy>=1.24.0
  - scikit-learn>=1.2.2
  - pytorch>=2.0.0
  - matplotlib>=3.7.1
  - networkx>=3.1
  - pygments>=2.15.1
  - tqdm>=4.65.0
  - jinja2>=3.1.2
  - click>=8.1.3
  - pip:
      - tree-sitter>=0.20.1
      - transformers>=4.29.0
      - fasttext>=0.9.2
      - black>=23.3.0
      - isort>=5.12.0
      - mypy>=1.3.0
      - pytest>=7.3.1
      - pytest-cov>=4.1.0
      - ruff>=0.0.270
      - pre-commit>=3.3.2
      - build>=0.10.0
